version: '3.8'

volumes:
  admin-data:
  redis_data:

networks:
  main-network:

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      main-network:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - fastapi
      - nestjs
      - nextjs
    networks:
      main-network:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=inal_2411
    volumes:
      - admin-data:/var/lib/postgresql/data
    networks:
      main-network:

  fastapi:
    build:
      context: ./backend-fastapi/
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - nestjs
    networks:
      main-network:

  nestjs:
    build:
      context: ./backend-nestjs/
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "4200:4200"
    depends_on:
      - nextjs
    environment:
      - NODE_ENV=production node dist/main.js
      - DATABASE_URL=postgresql://postgres:inal_2411@postgres:5432/filmflood
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - AWS_ACCESS_KEY=f280aec5d0cf4e258fcdefbefe5321ac
      - AWS_SECRET_ACCESS_KEY=3cefa4cd7b3e4350bc3d8bc9b146a062
      - AWS_ENDPOINT=https://s3.ru-1.storage.selcloud.ru
    networks:
      main-network:

  nextjs:
    build:
      context: ./frontend-nextjs/
      dockerfile: Dockerfile
    container_name: nextjs
    depends_on:
      - redis
      - postgres
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      main-network:
